#!/usr/bin/env bash
# Builds fluent_scene for the browser: the CPU renderer, the Scene document
# layer, and the flat C API, as an ES module. With --webgpu (Phase W3) the
# WebGPU backend is compiled in too, its WGSL machine-translated from the
# same GLSL the Vulkan backend embeds — never hand-ported.
#
#   source ~/emsdk/emsdk_env.sh && ./wasm/build.sh [--cjk] [--webgpu]
#
# --cjk embeds NotoSansCJK (~19 MB) for Japanese text; the default embeds
# DejaVuSans (~750 KB, Latin) to keep the module small. The font lands on
# the virtual FS at a path the renderer's candidate list already probes.
#
# --webgpu runs the glslc → naga pipe (host tools; robot image has both):
# each backend/vulkan/shaders source compiles with -DFS_WEBGPU (push
# constants become the group-1 uniform block, see push_common.glsl), naga
# rewrites the SPIR-V as WGSL, and the result embeds into wasm/gen/ as raw
# string literals for webgpu_renderer.cpp.
set -euo pipefail
cd "$(dirname "$0")/.."

FONT=/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
WEBGPU=0
for arg in "$@"; do
  case "$arg" in
    --cjk) FONT=/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc ;;
    --webgpu) WEBGPU=1 ;;
    *) echo "unknown flag: $arg" >&2; exit 2 ;;
  esac
done

EXTRA_SRC=()
EXTRA_FLAGS=()
if [[ $WEBGPU == 1 ]]; then
  GLSLC=${GLSLC:-$(command -v glslc || echo /usr/bin/glslc)}
  NAGA=${NAGA:-$(command -v naga || echo "$HOME/.cargo/bin/naga")}
  SHADER_DIR=backend/vulkan/shaders
  GEN=wasm/gen
  mkdir -p "$GEN"
  HDR=$GEN/shaders_wgsl.h
  {
    echo "// generated by wasm/build.sh --webgpu — do not edit."
    echo "// GLSL (backend/vulkan/shaders) → glslc -DFS_WEBGPU → naga → WGSL."
    echo "#pragma once"
  } > "$HDR"
  for s in quad.vert fullscreen.vert shape_mask.frag glyph_mask.frag \
           mask_composite.frag shape_color.frag image.frag filter.frag \
           filter_state.frag blur.frag composite.frag unpremul.frag present.frag; do
    "$GLSLC" -O -DFS_WEBGPU -I include -I "$SHADER_DIR" \
      -o "$GEN/$s.spv" "$SHADER_DIR/$s"
    "$NAGA" "$GEN/$s.spv" "$GEN/$s.wgsl"
    # quad.vert → kQuadVertWgsl (mirrors the Vulkan .inc constant names)
    name=$(echo "$s" | sed -E 's/(^|[._])([a-z])/\U\2/g')
    {
      echo "static const char k${name}Wgsl[] = R\"__wgsl("
      cat "$GEN/$s.wgsl"
      echo ")__wgsl\";"
    } >> "$HDR"
    rm "$GEN/$s.spv"
  done
  EXTRA_SRC=(src/webgpu_renderer.cpp)
  EXTRA_FLAGS=(--use-port=emdawnwebgpu -DFS_HAVE_WEBGPU=1 -I "$GEN" -I "$SHADER_DIR")
fi

mkdir -p wasm/dist
em++ -O2 -std=c++17 -msimd128 -I include \
  src/stage.cpp src/text_atlas.cpp src/cpu_renderer.cpp src/ui.cpp src/effects.cpp \
  src/fvs/diagnostics.cpp src/fvs/sha256.cpp src/fvs/yaml_parser.cpp \
  src/fvs/schema.cpp src/fvs/parser.cpp src/fvs/writer.cpp src/fvs/compiler.cpp \
  src/fvs/describe.cpp src/fvs/linter.cpp src/fvs/inspector.cpp \
  wasm/api.cpp "${EXTRA_SRC[@]}" \
  --use-port=freetype --use-port=harfbuzz \
  --embed-file "$FONT@$FONT" \
  "${EXTRA_FLAGS[@]}" \
  -sALLOW_MEMORY_GROWTH=1 \
  -sMODULARIZE=1 -sEXPORT_ES6=1 -sEXPORT_NAME=createFluentScene \
  -sEXPORTED_RUNTIME_METHODS=cwrap,HEAPU8,HEAPF32,stringToNewUTF8 \
  -sENVIRONMENT=web,node \
  -o wasm/dist/fluent_scene.mjs
ls -la wasm/dist/
