// webgpu_renderer.cpp — the browser GPU backend (§11, Phase W3).
//
// Structure mirrors vulkan_renderer.cpp draw-for-draw: the shared plan
// (render_shared.hpp) makes the same offscreen decisions and extents, the
// shared shape/filter bodies run as WGSL machine-translated from the very
// SPIR-V the Vulkan backend embeds (wasm/build.sh --webgpu; never
// hand-ported), coverage masks union multi-part content with MAX blending,
// and the four blend modes are the same fixed-function equations. What
// differs is only the browser's reality:
//
//  - push constants → one uniform buffer, 256-byte slots, dynamic offsets
//    (group 1; group 0 keeps the texture/sampler or storage bindings).
//  - float32 render targets are not blendable in core WebGPU → the working
//    targets are rgba16float/r16float. Half precision is far inside the
//    golden tolerance for anything the compositor computes.
//  - no clamp-to-border sampler → composite.frag emulates the transparent
//    border under FS_WEBGPU (exact bilinear ramp; see the shader).
//  - no blocking readback → the primary path presents into the canvas
//    (present.frag, canvas alphaMode "premultiplied" — pixel-equal to the
//    CPU path's putImageData compositing); pixel comparison goes through
//    the async readbackBegin/readbackPixels pair instead.
//  - device acquisition is async → construction starts the request chain
//    and the host polls status() until Ready.

#include "fluent_scene/webgpu_renderer.hpp"

#ifdef FS_HAVE_WEBGPU

#include <webgpu/webgpu.h>

#include <algorithm>
#include <cmath>
#include <cstdio>
#include <cstring>
#include <map>
#include <string>
#include <variant>
#include <vector>

#include "fluent_scene/stage.hpp"
#include "render_shared.hpp"
#include "text_atlas.hpp"

// Draw-mode ids shared with shape_mask.frag.
#include "shape_modes.h"

// WGSL sources generated by wasm/build.sh --webgpu (glslc → naga).
#include "shaders_wgsl.h"

namespace fluent_scene {

namespace {

using plan::dashSegments;
using plan::IRect;
using plan::pathSegments;
using plan::rectPad;
using plan::rectUnion;
using plan::scaleOf;
using plan::Seg;
using plan::segBounds;
using plan::targetBBox;

// The per-draw constant block — must match push_common.glsl exactly
// (VulkanRenderer::Push under another delivery mechanism).
struct Push {
    float rect[4];
    float meta[4];
    float inv0[4];
    float inv1[4];
    float pa[4];
    float pb[4];
    float px2[4];
    float color[4];
};
static_assert(sizeof(Push) == 128, "constant block must match push_common.glsl");

void setInv(Push& p, const Mat23& inv) {
    p.inv0[0] = inv.a;
    p.inv0[1] = inv.c;
    p.inv0[2] = inv.tx;
    p.inv1[0] = inv.b;
    p.inv1[1] = inv.d;
    p.inv1[2] = inv.ty;
}

void setRect(Push& p, IRect r) {
    p.rect[0] = static_cast<float>(r.x0);
    p.rect[1] = static_cast<float>(r.y0);
    p.rect[2] = static_cast<float>(r.x1 - r.x0);
    p.rect[3] = static_cast<float>(r.y1 - r.y0);
}

void setColor(Push& p, Color c) {
    p.color[0] = c.r;
    p.color[1] = c.g;
    p.color[2] = c.b;
    p.color[3] = c.a;
}

std::string toString(WGPUStringView s) {
    return s.data == nullptr ? std::string()
                             : (s.length == WGPU_STRLEN ? std::string(s.data)
                                                        : std::string(s.data, s.length));
}

WGPUStringView view(const char* s) { return {s, WGPU_STRLEN}; }

}  // namespace

// ===========================================================================
// Impl
// ===========================================================================

struct WebGPURenderer::Impl {
    // ---- device (arrives asynchronously) -----------------------------------

    WebGPURenderer::Options options;
    Status status = Status::Initializing;
    std::string error;

    WGPUInstance instance = nullptr;
    WGPUAdapter adapter = nullptr;
    WGPUDevice device = nullptr;
    WGPUQueue queue = nullptr;
    WGPUSurface surface = nullptr;  // the canvas; null = offscreen only
    WGPUTextureFormat surface_format = WGPUTextureFormat_BGRA8Unorm;
    int surface_w = 0, surface_h = 0;  // configured size

    // ---- resources ---------------------------------------------------------

    struct Tex {
        WGPUTexture tex = nullptr;
        WGPUTextureView view = nullptr;
        int w = 0, h = 0;
        WGPUTextureFormat format = WGPUTextureFormat_Undefined;
        bool in_use = false;      // transient-pool bookkeeping
        bool needs_clear = true;  // first ensureTarget clears
    };

    // unique_ptr: acquireTransient hands out raw pointers that must stay
    // stable while the pool grows.
    std::vector<std::unique_ptr<Tex>> transient_pool;
    Tex canvas;    // premultiplied rgba16float working target
    Tex out_rgba;  // rgba8 conversion target (readback path)

    // Async readback (one in flight).
    WGPUBuffer readback_buf = nullptr;
    uint32_t readback_bpr = 0;  // 256-aligned bytes per row
    int readback_w = 0, readback_h = 0;
    bool readback_pending = false;
    bool readback_ready = false;
    std::vector<uint8_t> out_pixels;

    // The "push constant" arena: 256-byte slots (the spec's dynamic-offset
    // alignment), one slot per draw, chunked so a heavy frame just grows.
    static constexpr uint32_t kPushStride = 256;
    static constexpr uint32_t kChunkBytes = 1u << 20;  // 4096 draws per chunk
    struct PushChunk {
        WGPUBuffer buf = nullptr;
        WGPUBindGroup group = nullptr;
        std::vector<uint8_t> cpu;
        uint32_t used = 0;
    };
    std::vector<PushChunk> push_chunks;
    size_t push_chunk_i = 0;

    WGPUBuffer points_buf = nullptr;  // polygon points, rewritten per frame
    WGPUBuffer dummy_buf = nullptr;   // bound when a draw needs no points
    WGPUBindGroup points_group = nullptr;
    WGPUBindGroup dummy_group = nullptr;

    // Keyed by the source pixels, not the layer: any number of layers can
    // borrow the same texture and the frame transfers exactly once.
    struct ContentTex {
        Tex tex;
        uint64_t frame_used = 0;
    };
    std::map<const void*, ContentTex> image_cache;
    // A stateful filter's persistent ping-pong field, keyed by (layer
    // identity, filter mode); swept with NO grace period — the key is the
    // layer's address, and a reused address must cold-start, not inherit a
    // stranger's field (persistent_buffers P1).
    struct FilterState {
        Tex ping;
        Tex pong;
        uint64_t frame_used = 0;
    };
    std::map<std::pair<const void*, int>, FilterState> state_cache;
    Tex atlas_tex;
    uint64_t atlas_uploaded_revision = 0;
    uint64_t frame_counter = 0;

    detail::TextAtlas atlas;
    bool atlas_tried = false;

    // ---- samplers / bind group layouts / pipelines -------------------------

    WGPUSampler sampler_nearest = nullptr;  // filters, masks (clamp edge)
    WGPUSampler sampler_linear = nullptr;   // images, atlas, composite
    // (Vulkan's clamp-to-border sampler has no WebGPU equivalent;
    // composite.frag emulates the border under FS_WEBGPU.)

    WGPUBindGroupLayout bgl_tex = nullptr;   // 0: texture, 1: sampler
    WGPUBindGroupLayout bgl_ssbo = nullptr;  // 0: read-only storage
    WGPUBindGroupLayout bgl_push = nullptr;  // 0: uniform, dynamic offset
    WGPUPipelineLayout layout_tex = nullptr;
    WGPUPipelineLayout layout_ssbo = nullptr;

    WGPURenderPipeline pipe_mask_shape = nullptr;  // r16float, MAX
    WGPURenderPipeline pipe_mask_glyph = nullptr;  // r16float, MAX
    WGPURenderPipeline pipe_mask_comp[4] = {};     // rgba16float, blend modes
    WGPURenderPipeline pipe_shape_color[4] = {};
    WGPURenderPipeline pipe_image[4] = {};
    WGPURenderPipeline pipe_composite[4] = {};
    WGPURenderPipeline pipe_filter = nullptr;
    WGPURenderPipeline pipe_filter_state = nullptr;
    WGPURenderPipeline pipe_layer_mask = nullptr;
    WGPURenderPipeline pipe_blur = nullptr;
    WGPURenderPipeline pipe_unpremul = nullptr;  // rgba8unorm
    WGPURenderPipeline pipe_present = nullptr;   // surface format

    // ---- recording state ---------------------------------------------------

    WGPUCommandEncoder encoder = nullptr;
    WGPURenderPassEncoder pass = nullptr;
    Tex* bound_target = nullptr;
    std::vector<WGPUBindGroup> frame_groups;  // released after submit

    struct TextRun {
        std::vector<detail::TextAtlas::GlyphQuad> quads;
        float width = 0;
    };
    std::map<std::string, TextRun> text_runs;
    std::map<const Layer*, uint32_t> polygon_offsets;
    std::vector<Vec2> polygon_points;

    ~Impl() { destroy(); }

    void fail(const std::string& what) {
        if (status != Status::Error) {
            status = Status::Error;
            error = what;
        }
        std::fprintf(stderr, "fluent_scene webgpu: %s\n", what.c_str());
    }

    // =======================================================================
    // async init chain: instance → surface → adapter → device → pipelines
    // =======================================================================

    void start() {
        instance = wgpuCreateInstance(nullptr);
        if (instance == nullptr) {
            fail("wgpuCreateInstance failed (no WebGPU in this browser?)");
            return;
        }
        if (!options.canvas_selector.empty()) {
            WGPUEmscriptenSurfaceSourceCanvasHTMLSelector sel =
                WGPU_EMSCRIPTEN_SURFACE_SOURCE_CANVAS_HTML_SELECTOR_INIT;
            sel.selector = view(options.canvas_selector.c_str());
            WGPUSurfaceDescriptor sd = {};
            sd.nextInChain = &sel.chain;
            surface = wgpuInstanceCreateSurface(instance, &sd);
            if (surface == nullptr) {
                fail("wgpuInstanceCreateSurface failed for '" + options.canvas_selector + "'");
                return;
            }
        }
        WGPURequestAdapterOptions opts = WGPU_REQUEST_ADAPTER_OPTIONS_INIT;
        opts.compatibleSurface = surface;
        WGPURequestAdapterCallbackInfo cb = {};
        cb.mode = WGPUCallbackMode_AllowSpontaneous;
        cb.callback = &Impl::onAdapter;
        cb.userdata1 = this;
        wgpuInstanceRequestAdapter(instance, &opts, cb);
    }

    static void onAdapter(WGPURequestAdapterStatus s, WGPUAdapter adapter, WGPUStringView msg,
                          void* userdata1, void*) {
        Impl* self = static_cast<Impl*>(userdata1);
        if (s != WGPURequestAdapterStatus_Success) {
            self->fail("adapter request failed: " + toString(msg));
            return;
        }
        self->adapter = adapter;

        WGPUDeviceDescriptor dd = WGPU_DEVICE_DESCRIPTOR_INIT;
        dd.deviceLostCallbackInfo.mode = WGPUCallbackMode_AllowSpontaneous;
        dd.deviceLostCallbackInfo.callback = &Impl::onDeviceLost;
        dd.deviceLostCallbackInfo.userdata1 = self;
        dd.uncapturedErrorCallbackInfo.callback = &Impl::onUncapturedError;
        dd.uncapturedErrorCallbackInfo.userdata1 = self;
        WGPURequestDeviceCallbackInfo cb = {};
        cb.mode = WGPUCallbackMode_AllowSpontaneous;
        cb.callback = &Impl::onDevice;
        cb.userdata1 = self;
        wgpuAdapterRequestDevice(adapter, &dd, cb);
    }

    static void onDevice(WGPURequestDeviceStatus s, WGPUDevice device, WGPUStringView msg,
                         void* userdata1, void*) {
        Impl* self = static_cast<Impl*>(userdata1);
        if (s != WGPURequestDeviceStatus_Success) {
            self->fail("device request failed: " + toString(msg));
            return;
        }
        self->device = device;
        self->queue = wgpuDeviceGetQueue(device);
        if (self->surface != nullptr) {
            WGPUSurfaceCapabilities caps = WGPU_SURFACE_CAPABILITIES_INIT;
            if (wgpuSurfaceGetCapabilities(self->surface, self->adapter, &caps) ==
                    WGPUStatus_Success &&
                caps.formatCount > 0) {
                self->surface_format = caps.formats[0];
            }
            wgpuSurfaceCapabilitiesFreeMembers(caps);
        }
        self->createFixedResources();
        self->createPipelines();
        if (self->status == Status::Initializing) {
            self->status = Status::Ready;
        }
    }

    static void onDeviceLost(WGPUDevice const*, WGPUDeviceLostReason reason, WGPUStringView msg,
                             void* userdata1, void*) {
        Impl* self = static_cast<Impl*>(userdata1);
        if (reason == WGPUDeviceLostReason_Destroyed) {
            return;  // our own teardown
        }
        self->fail("device lost: " + toString(msg));
    }

    static void onUncapturedError(WGPUDevice const*, WGPUErrorType, WGPUStringView msg,
                                  void* userdata1, void*) {
        // Validation storms should be loud but not fatal: the frame keeps
        // rendering (possibly wrong) and the console names the bug.
        Impl* self = static_cast<Impl*>(userdata1);
        if (self->uncaptured_logged < 16) {
            ++self->uncaptured_logged;
            std::fprintf(stderr, "fluent_scene webgpu: uncaptured error: %s\n",
                         toString(msg).c_str());
        }
    }
    int uncaptured_logged = 0;

    // =======================================================================
    // fixed resources
    // =======================================================================

    WGPUBuffer createBuffer(uint64_t size, WGPUBufferUsage usage) {
        WGPUBufferDescriptor bd = WGPU_BUFFER_DESCRIPTOR_INIT;
        bd.usage = usage;
        bd.size = size;
        return wgpuDeviceCreateBuffer(device, &bd);
    }

    Tex createTex(int w, int h, WGPUTextureFormat format, WGPUTextureUsage usage) {
        Tex t;
        t.w = w;
        t.h = h;
        t.format = format;
        WGPUTextureDescriptor td = WGPU_TEXTURE_DESCRIPTOR_INIT;
        td.usage = usage;
        td.size = {static_cast<uint32_t>(w), static_cast<uint32_t>(h), 1};
        td.format = format;
        t.tex = wgpuDeviceCreateTexture(device, &td);
        t.view = wgpuTextureCreateView(t.tex, nullptr);
        return t;
    }

    void destroyTex(Tex& t) {
        if (t.view != nullptr) {
            wgpuTextureViewRelease(t.view);
        }
        if (t.tex != nullptr) {
            wgpuTextureRelease(t.tex);
        }
        t = {};
    }

    void createFixedResources() {
        const auto makeSampler = [&](WGPUFilterMode filter) {
            WGPUSamplerDescriptor sd = WGPU_SAMPLER_DESCRIPTOR_INIT;
            sd.addressModeU = WGPUAddressMode_ClampToEdge;
            sd.addressModeV = WGPUAddressMode_ClampToEdge;
            sd.addressModeW = WGPUAddressMode_ClampToEdge;
            sd.magFilter = filter;
            sd.minFilter = filter;
            return wgpuDeviceCreateSampler(device, &sd);
        };
        sampler_nearest = makeSampler(WGPUFilterMode_Nearest);
        sampler_linear = makeSampler(WGPUFilterMode_Linear);

        {
            // Bindings 2/3 carry a filter's image parameter (`lut` grade),
            // bindings 4/5 a stateful filter's persistent field (rgba32f is
            // not filterable in core WebGPU, so 4 is unfilterable-float and
            // 5 a non-filtering sampler — state reads are textureLoad
            // anyway); shaders that never declare them just leave them
            // unread, and texGroup self-binds the source when not given.
            WGPUBindGroupLayoutEntry entries[6] = {
                WGPU_BIND_GROUP_LAYOUT_ENTRY_INIT, WGPU_BIND_GROUP_LAYOUT_ENTRY_INIT,
                WGPU_BIND_GROUP_LAYOUT_ENTRY_INIT, WGPU_BIND_GROUP_LAYOUT_ENTRY_INIT,
                WGPU_BIND_GROUP_LAYOUT_ENTRY_INIT, WGPU_BIND_GROUP_LAYOUT_ENTRY_INIT};
            for (uint32_t i = 0; i < 6; ++i) {
                entries[i].binding = i;
                entries[i].visibility = WGPUShaderStage_Fragment;
                if (i % 2 == 0) {
                    entries[i].texture.sampleType = i == 4
                                                        ? WGPUTextureSampleType_UnfilterableFloat
                                                        : WGPUTextureSampleType_Float;
                    entries[i].texture.viewDimension = WGPUTextureViewDimension_2D;
                } else {
                    entries[i].sampler.type = i == 5 ? WGPUSamplerBindingType_NonFiltering
                                                     : WGPUSamplerBindingType_Filtering;
                }
            }
            WGPUBindGroupLayoutDescriptor ld = {};
            ld.entryCount = 6;
            ld.entries = entries;
            bgl_tex = wgpuDeviceCreateBindGroupLayout(device, &ld);
        }
        {
            WGPUBindGroupLayoutEntry entry = WGPU_BIND_GROUP_LAYOUT_ENTRY_INIT;
            entry.binding = 0;
            entry.visibility = WGPUShaderStage_Fragment;
            entry.buffer.type = WGPUBufferBindingType_ReadOnlyStorage;
            WGPUBindGroupLayoutDescriptor ld = {};
            ld.entryCount = 1;
            ld.entries = &entry;
            bgl_ssbo = wgpuDeviceCreateBindGroupLayout(device, &ld);
        }
        {
            WGPUBindGroupLayoutEntry entry = WGPU_BIND_GROUP_LAYOUT_ENTRY_INIT;
            entry.binding = 0;
            entry.visibility = WGPUShaderStage_Vertex | WGPUShaderStage_Fragment;
            entry.buffer.type = WGPUBufferBindingType_Uniform;
            entry.buffer.hasDynamicOffset = 1;
            entry.buffer.minBindingSize = sizeof(Push);
            WGPUBindGroupLayoutDescriptor ld = {};
            ld.entryCount = 1;
            ld.entries = &entry;
            bgl_push = wgpuDeviceCreateBindGroupLayout(device, &ld);
        }
        const auto makePipeLayout = [&](WGPUBindGroupLayout group0) {
            WGPUBindGroupLayout groups[2] = {group0, bgl_push};
            WGPUPipelineLayoutDescriptor ld = {};
            ld.bindGroupLayoutCount = 2;
            ld.bindGroupLayouts = groups;
            return wgpuDeviceCreatePipelineLayout(device, &ld);
        };
        layout_tex = makePipeLayout(bgl_tex);
        layout_ssbo = makePipeLayout(bgl_ssbo);

        points_buf = createBuffer(sizeof(float) * 2 * 65536,
                                  WGPUBufferUsage_Storage | WGPUBufferUsage_CopyDst);
        dummy_buf = createBuffer(64, WGPUBufferUsage_Storage | WGPUBufferUsage_CopyDst);
        points_group = ssboGroupFor(points_buf);
        dummy_group = ssboGroupFor(dummy_buf);
    }

    WGPUBindGroup ssboGroupFor(WGPUBuffer buf) {
        WGPUBindGroupEntry entry = WGPU_BIND_GROUP_ENTRY_INIT;
        entry.binding = 0;
        entry.buffer = buf;
        entry.size = WGPU_WHOLE_SIZE;
        WGPUBindGroupDescriptor bd = {};
        bd.layout = bgl_ssbo;
        bd.entryCount = 1;
        bd.entries = &entry;
        return wgpuDeviceCreateBindGroup(device, &bd);
    }

    // =======================================================================
    // pipelines
    // =======================================================================

    WGPUShaderModule makeModule(const char* wgsl) {
        WGPUShaderSourceWGSL src = WGPU_SHADER_SOURCE_WGSL_INIT;
        src.code = view(wgsl);
        WGPUShaderModuleDescriptor sd = {};
        sd.nextInChain = &src.chain;
        return wgpuDeviceCreateShaderModule(device, &sd);
    }

    // The four blend modes as fixed-function factors — the same equations
    // the CPU reference documents in blendPremul().
    static WGPUBlendState blendState(int mode) {
        WGPUBlendState s = {};
        s.alpha = {WGPUBlendOperation_Add, WGPUBlendFactor_One,
                   WGPUBlendFactor_OneMinusSrcAlpha};
        s.color.operation = WGPUBlendOperation_Add;
        switch (static_cast<Blend>(mode)) {
            case Blend::Normal:
                s.color.srcFactor = WGPUBlendFactor_One;
                s.color.dstFactor = WGPUBlendFactor_OneMinusSrcAlpha;
                break;
            case Blend::Add:
                s.color.srcFactor = WGPUBlendFactor_One;
                s.color.dstFactor = WGPUBlendFactor_One;
                break;
            case Blend::Multiply:
                s.color.srcFactor = WGPUBlendFactor_Dst;
                s.color.dstFactor = WGPUBlendFactor_OneMinusSrcAlpha;
                break;
            case Blend::Screen:
                s.color.srcFactor = WGPUBlendFactor_OneMinusDst;
                s.color.dstFactor = WGPUBlendFactor_One;
                break;
        }
        return s;
    }

    static WGPUBlendState maxBlendState() {
        WGPUBlendState s = {};
        s.color = {WGPUBlendOperation_Max, WGPUBlendFactor_One, WGPUBlendFactor_One};
        s.alpha = {WGPUBlendOperation_Max, WGPUBlendFactor_One, WGPUBlendFactor_One};
        return s;
    }

    WGPURenderPipeline makePipeline(WGPUShaderModule vert, WGPUShaderModule frag,
                                    WGPUPipelineLayout layout, WGPUTextureFormat color_format,
                                    const WGPUBlendState* blend, bool strip) {
        WGPUColorTargetState target = WGPU_COLOR_TARGET_STATE_INIT;
        target.format = color_format;
        target.blend = blend;  // null = overwrite
        WGPUFragmentState fs = WGPU_FRAGMENT_STATE_INIT;
        fs.module = frag;
        fs.entryPoint = view("main");
        fs.targetCount = 1;
        fs.targets = &target;
        WGPURenderPipelineDescriptor pd = WGPU_RENDER_PIPELINE_DESCRIPTOR_INIT;
        pd.layout = layout;
        pd.vertex.module = vert;
        pd.vertex.entryPoint = view("main");
        pd.primitive.topology =
            strip ? WGPUPrimitiveTopology_TriangleStrip : WGPUPrimitiveTopology_TriangleList;
        pd.fragment = &fs;
        return wgpuDeviceCreateRenderPipeline(device, &pd);
    }

    void createPipelines() {
        WGPUShaderModule quad = makeModule(kQuadVertWgsl);
        WGPUShaderModule fullscreen = makeModule(kFullscreenVertWgsl);
        WGPUShaderModule shape_mask = makeModule(kShapeMaskFragWgsl);
        WGPUShaderModule glyph_mask = makeModule(kGlyphMaskFragWgsl);
        WGPUShaderModule mask_comp = makeModule(kMaskCompositeFragWgsl);
        WGPUShaderModule shape_color = makeModule(kShapeColorFragWgsl);
        WGPUShaderModule image = makeModule(kImageFragWgsl);
        WGPUShaderModule filter = makeModule(kFilterFragWgsl);
        WGPUShaderModule filter_state = makeModule(kFilterStateFragWgsl);
        WGPUShaderModule layer_mask = makeModule(kLayerMaskFragWgsl);
        WGPUShaderModule blur = makeModule(kBlurFragWgsl);
        WGPUShaderModule composite = makeModule(kCompositeFragWgsl);
        WGPUShaderModule unpremul = makeModule(kUnpremulFragWgsl);
        WGPUShaderModule present = makeModule(kPresentFragWgsl);

        const WGPUTextureFormat kColor = WGPUTextureFormat_RGBA16Float;
        const WGPUTextureFormat kMask = WGPUTextureFormat_R16Float;
        const WGPUBlendState max_blend = maxBlendState();
        WGPUBlendState blends[4];
        for (int b = 0; b < 4; ++b) {
            blends[b] = blendState(b);
        }

        pipe_mask_shape = makePipeline(quad, shape_mask, layout_ssbo, kMask, &max_blend, true);
        pipe_mask_glyph = makePipeline(quad, glyph_mask, layout_tex, kMask, &max_blend, true);
        for (int b = 0; b < 4; ++b) {
            pipe_mask_comp[b] =
                makePipeline(quad, mask_comp, layout_tex, kColor, &blends[b], true);
            pipe_shape_color[b] =
                makePipeline(quad, shape_color, layout_ssbo, kColor, &blends[b], true);
            pipe_image[b] = makePipeline(quad, image, layout_tex, kColor, &blends[b], true);
            pipe_composite[b] =
                makePipeline(quad, composite, layout_tex, kColor, &blends[b], true);
        }
        pipe_filter = makePipeline(fullscreen, filter, layout_tex, kColor, nullptr, false);
        pipe_filter_state = makePipeline(fullscreen, filter_state, layout_tex,
                                         WGPUTextureFormat_RGBA32Float, nullptr, false);
        pipe_layer_mask = makePipeline(fullscreen, layer_mask, layout_tex, kColor, nullptr, false);
        pipe_blur = makePipeline(fullscreen, blur, layout_tex, kColor, nullptr, false);
        pipe_unpremul = makePipeline(fullscreen, unpremul, layout_tex,
                                     WGPUTextureFormat_RGBA8Unorm, nullptr, false);
        if (surface != nullptr) {
            pipe_present =
                makePipeline(fullscreen, present, layout_tex, surface_format, nullptr, false);
        }

        for (WGPUShaderModule m : {quad, fullscreen, shape_mask, glyph_mask, mask_comp,
                                   shape_color, image, filter, filter_state, layer_mask, blur,
                                   composite, unpremul, present}) {
            wgpuShaderModuleRelease(m);
        }
    }

    void destroy() {
        for (auto& t : transient_pool) {
            destroyTex(*t);
        }
        for (auto& [_, tex] : image_cache) {
            destroyTex(tex.tex);
        }
        for (auto& [_, st] : state_cache) {
            destroyTex(st.ping);
            destroyTex(st.pong);
        }
        destroyTex(atlas_tex);
        destroyTex(canvas);
        destroyTex(out_rgba);
        const auto releaseBuffer = [](WGPUBuffer& b) {
            if (b != nullptr) {
                wgpuBufferRelease(b);
                b = nullptr;
            }
        };
        releaseBuffer(readback_buf);
        releaseBuffer(points_buf);
        releaseBuffer(dummy_buf);
        for (PushChunk& c : push_chunks) {
            if (c.group != nullptr) {
                wgpuBindGroupRelease(c.group);
            }
            releaseBuffer(c.buf);
        }
        const auto releasePipe = [](WGPURenderPipeline p) {
            if (p != nullptr) {
                wgpuRenderPipelineRelease(p);
            }
        };
        releasePipe(pipe_mask_shape);
        releasePipe(pipe_mask_glyph);
        for (int b = 0; b < 4; ++b) {
            releasePipe(pipe_mask_comp[b]);
            releasePipe(pipe_shape_color[b]);
            releasePipe(pipe_image[b]);
            releasePipe(pipe_composite[b]);
        }
        releasePipe(pipe_filter);
        releasePipe(pipe_filter_state);
        releasePipe(pipe_layer_mask);
        releasePipe(pipe_blur);
        releasePipe(pipe_unpremul);
        releasePipe(pipe_present);
        if (points_group != nullptr) {
            wgpuBindGroupRelease(points_group);
        }
        if (dummy_group != nullptr) {
            wgpuBindGroupRelease(dummy_group);
        }
        if (layout_tex != nullptr) {
            wgpuPipelineLayoutRelease(layout_tex);
        }
        if (layout_ssbo != nullptr) {
            wgpuPipelineLayoutRelease(layout_ssbo);
        }
        if (bgl_tex != nullptr) {
            wgpuBindGroupLayoutRelease(bgl_tex);
        }
        if (bgl_ssbo != nullptr) {
            wgpuBindGroupLayoutRelease(bgl_ssbo);
        }
        if (bgl_push != nullptr) {
            wgpuBindGroupLayoutRelease(bgl_push);
        }
        if (sampler_nearest != nullptr) {
            wgpuSamplerRelease(sampler_nearest);
        }
        if (sampler_linear != nullptr) {
            wgpuSamplerRelease(sampler_linear);
        }
        if (surface != nullptr) {
            wgpuSurfaceRelease(surface);
        }
        if (queue != nullptr) {
            wgpuQueueRelease(queue);
        }
        if (device != nullptr) {
            wgpuDeviceRelease(device);
        }
        if (adapter != nullptr) {
            wgpuAdapterRelease(adapter);
        }
        if (instance != nullptr) {
            wgpuInstanceRelease(instance);
        }
    }

    // =======================================================================
    // recording helpers
    // =======================================================================

    void endTarget() {
        if (bound_target != nullptr) {
            wgpuRenderPassEncoderEnd(pass);
            wgpuRenderPassEncoderRelease(pass);
            pass = nullptr;
            bound_target = nullptr;
        }
    }

    // Begins (or resumes with load) rendering into `img` — the WebGPU form
    // of Vulkan's suspend/resume dynamic rendering, so offscreen subtrees
    // can render mid-parent in the CPU recursion order.
    void ensureTarget(Tex& img) {
        if (bound_target == &img) {
            return;
        }
        endTarget();
        beginPass(img.view, img.needs_clear);
        img.needs_clear = false;
        bound_target = &img;
    }

    void beginPass(WGPUTextureView target_view, bool clear) {
        WGPURenderPassColorAttachment color = WGPU_RENDER_PASS_COLOR_ATTACHMENT_INIT;
        color.view = target_view;
        color.loadOp = clear ? WGPULoadOp_Clear : WGPULoadOp_Load;
        color.storeOp = WGPUStoreOp_Store;
        color.clearValue = {0, 0, 0, 0};
        WGPURenderPassDescriptor rd = WGPU_RENDER_PASS_DESCRIPTOR_INIT;
        rd.colorAttachmentCount = 1;
        rd.colorAttachments = &color;
        pass = wgpuCommandEncoderBeginRenderPass(encoder, &rd);
    }

    WGPUBindGroup texGroup(WGPUTextureView tex_view, WGPUSampler sampler,
                           WGPUTextureView image_param_view = nullptr,
                           WGPUSampler image_param_sampler = nullptr,
                           WGPUTextureView state_view = nullptr) {
        // Bindings 2/3 carry a filter's image parameter, 4/5 a stateful
        // filter's field; without one the source self-binds so the group
        // is always complete.
        if (image_param_view == nullptr) {
            image_param_view = tex_view;
            image_param_sampler = sampler;
        }
        if (state_view == nullptr) {
            state_view = tex_view;
        }
        WGPUBindGroupEntry entries[6] = {WGPU_BIND_GROUP_ENTRY_INIT, WGPU_BIND_GROUP_ENTRY_INIT,
                                         WGPU_BIND_GROUP_ENTRY_INIT, WGPU_BIND_GROUP_ENTRY_INIT,
                                         WGPU_BIND_GROUP_ENTRY_INIT, WGPU_BIND_GROUP_ENTRY_INIT};
        entries[0].binding = 0;
        entries[0].textureView = tex_view;
        entries[1].binding = 1;
        entries[1].sampler = sampler;
        entries[2].binding = 2;
        entries[2].textureView = image_param_view;
        entries[3].binding = 3;
        entries[3].sampler = image_param_sampler;
        entries[4].binding = 4;
        entries[4].textureView = state_view;
        entries[5].binding = 5;
        entries[5].sampler = sampler_nearest;
        WGPUBindGroupDescriptor bd = {};
        bd.layout = bgl_tex;
        bd.entryCount = 6;
        bd.entries = entries;
        WGPUBindGroup g = wgpuDeviceCreateBindGroup(device, &bd);
        frame_groups.push_back(g);
        return g;
    }

    // One 256-byte slot in the push arena; contents reach the GPU via the
    // pre-submit writeBuffer in flushPushChunks().
    struct PushSlot {
        WGPUBindGroup group;
        uint32_t offset;
    };
    PushSlot allocPush(const Push& push) {
        if (push_chunks.empty() || push_chunks[push_chunk_i].used + kPushStride > kChunkBytes) {
            if (!push_chunks.empty()) {
                ++push_chunk_i;
            }
            if (push_chunk_i >= push_chunks.size()) {
                PushChunk c;
                c.buf = createBuffer(kChunkBytes,
                                     WGPUBufferUsage_Uniform | WGPUBufferUsage_CopyDst);
                WGPUBindGroupEntry entry = WGPU_BIND_GROUP_ENTRY_INIT;
                entry.binding = 0;
                entry.buffer = c.buf;
                entry.size = sizeof(Push);
                WGPUBindGroupDescriptor bd = {};
                bd.layout = bgl_push;
                bd.entryCount = 1;
                bd.entries = &entry;
                c.group = wgpuDeviceCreateBindGroup(device, &bd);
                c.cpu.resize(kChunkBytes);
                push_chunks.push_back(std::move(c));
            }
        }
        PushChunk& c = push_chunks[push_chunk_i];
        std::memcpy(c.cpu.data() + c.used, &push, sizeof(Push));
        const uint32_t offset = c.used;
        c.used += kPushStride;
        return {c.group, offset};
    }

    void flushPushChunks() {
        for (PushChunk& c : push_chunks) {
            if (c.used > 0) {
                wgpuQueueWriteBuffer(queue, c.buf, 0, c.cpu.data(), c.used);
            }
        }
    }

    void drawQuad(WGPURenderPipeline pipeline, WGPUBindGroup group0, const Push& push) {
        wgpuRenderPassEncoderSetPipeline(pass, pipeline);
        wgpuRenderPassEncoderSetBindGroup(pass, 0, group0, 0, nullptr);
        const PushSlot slot = allocPush(push);
        wgpuRenderPassEncoderSetBindGroup(pass, 1, slot.group, 1, &slot.offset);
        wgpuRenderPassEncoderDraw(pass, 4, 1, 0, 0);
    }

    void drawFullscreen(WGPURenderPipeline pipeline, WGPUBindGroup group0, const Push& push) {
        wgpuRenderPassEncoderSetPipeline(pass, pipeline);
        wgpuRenderPassEncoderSetBindGroup(pass, 0, group0, 0, nullptr);
        const PushSlot slot = allocPush(push);
        wgpuRenderPassEncoderSetBindGroup(pass, 1, slot.group, 1, &slot.offset);
        wgpuRenderPassEncoderDraw(pass, 3, 1, 0, 0);
    }

    // ---- transient pool ----------------------------------------------------

    Tex* acquireTransient(int w, int h, WGPUTextureFormat format) {
        for (auto& t : transient_pool) {
            if (!t->in_use && t->w == w && t->h == h && t->format == format) {
                t->in_use = true;
                t->needs_clear = true;
                return t.get();
            }
        }
        transient_pool.push_back(std::make_unique<Tex>(createTex(
            w, h, format, WGPUTextureUsage_RenderAttachment | WGPUTextureUsage_TextureBinding)));
        transient_pool.back()->in_use = true;
        transient_pool.back()->needs_clear = true;
        return transient_pool.back().get();
    }

    void releaseAllTransients() {
        for (auto& t : transient_pool) {
            t->in_use = false;
        }
    }

    // ---- uploads (queue writes land before the frame's submit) -------------

    void uploadTex(Tex& t, const void* pixels, uint32_t bytes_per_row) {
        WGPUTexelCopyTextureInfo dst = WGPU_TEXEL_COPY_TEXTURE_INFO_INIT;
        dst.texture = t.tex;
        WGPUTexelCopyBufferLayout layout = {};
        layout.bytesPerRow = bytes_per_row;
        layout.rowsPerImage = static_cast<uint32_t>(t.h);
        WGPUExtent3D size = {static_cast<uint32_t>(t.w), static_cast<uint32_t>(t.h), 1};
        wgpuQueueWriteTexture(queue, &dst, pixels,
                              static_cast<size_t>(bytes_per_row) * t.h, &layout, &size);
    }

    // =======================================================================
    // text
    // =======================================================================

    void ensureAtlas() {
        if (atlas.ready() || atlas_tried) {
            return;
        }
        atlas_tried = true;
        detail::initAtlasWithFallback(atlas, options.font_file, options.font_pixel_size);
    }

    Rect measureText(const TextContent& c) {
        ensureAtlas();
        if (!atlas.ready()) {
            return {};
        }
        const float s = c.size / static_cast<float>(atlas.pixelSize());
        const float w = atlas.measure(c.utf8) * s;
        const float h = atlas.lineHeight() * s;
        float x = c.position.x;
        if (c.align == Align::Center) {
            x -= w * 0.5f;
        } else if (c.align == Align::Right) {
            x -= w;
        }
        return {x, c.position.y, w, h};
    }

    const TextRun& textRun(const std::string& utf8) {
        auto it = text_runs.find(utf8);
        if (it == text_runs.end()) {
            TextRun run;
            atlas.layout(utf8, 0, 0, 4096, run.quads);
            run.width = atlas.measure(utf8);
            it = text_runs.emplace(utf8, std::move(run)).first;
        }
        return it->second;
    }

    static std::string boxLabel(const Box& box) {
        std::string label = box.label;
        if (box.score > 0) {
            char score[16];
            std::snprintf(score, sizeof score, "%.2f", box.score);
            label += (label.empty() ? "" : " ") + std::string(score);
        }
        return label;
    }

    // Pre-pass: warm every glyph this frame will draw, gather polygon
    // points, and upload image content — all queue writes, all before submit.
    void prepassLayer(const Layer& layer) {
        if (layer.hidden()) {
            return;
        }
        const Content& content = layer.content();
        if (const auto* t = std::get_if<TextContent>(&content)) {
            ensureAtlas();
            if (atlas.ready()) {
                textRun(t->utf8);
            }
        } else if (const auto* b = std::get_if<BoxesContent>(&content)) {
            if (b->show_label) {
                ensureAtlas();
                if (atlas.ready()) {
                    for (const Box& box : b->smoothed) {
                        const std::string label = boxLabel(box);
                        if (!label.empty()) {
                            textRun(label);
                        }
                    }
                }
            }
        } else if (const auto* p = std::get_if<PolygonContent>(&content)) {
            if (layer.thickness() <= 0 && p->points.size() >= 3) {
                polygon_offsets[&layer] = static_cast<uint32_t>(polygon_points.size());
                polygon_points.insert(polygon_points.end(), p->points.begin(), p->points.end());
            }
        } else if (const auto* img = std::get_if<ImageContent>(&content)) {
            if (img->view.valid()) {
                uploadContentImage(img->view);
            }
        }
        // Filter image parameters (`lut` grades) ride the same upload path
        // and cache as image content; alpha is opaque, so the premultiply
        // staging is a no-op for them.
        for (const Filter& f : layer.filters()) {
            if (f.image.valid()) {
                uploadContentImage(f.image);
            }
        }
        if (layer.maskValue().valid()) {
            uploadContentImage(layer.maskValue());
        }
        for (const auto& child : layer.sublayers()) {
            prepassLayer(*child);
        }
    }

    void uploadContentImage(const ImageView& v) {
        auto& entry = image_cache[v.pixels];
        if (entry.frame_used == frame_counter) {
            return;  // shared source already transferred this frame
        }
        if (entry.tex.w != static_cast<int>(v.width) ||
            entry.tex.h != static_cast<int>(v.height)) {
            destroyTex(entry.tex);
            entry.tex = createTex(static_cast<int>(v.width), static_cast<int>(v.height),
                                  WGPUTextureFormat_RGBA8Unorm,
                                  WGPUTextureUsage_TextureBinding | WGPUTextureUsage_CopyDst);
        }
        entry.frame_used = frame_counter;
        // Premultiply during staging so bilinear filtering matches the CPU
        // reference (which premultiplies per tap before interpolating).
        const uint32_t stride = v.stride();
        std::vector<uint8_t> premul(static_cast<size_t>(v.width) * v.height * 4);
        for (uint32_t y = 0; y < v.height; ++y) {
            const uint8_t* src = v.pixels + static_cast<size_t>(y) * stride;
            uint8_t* dst = premul.data() + static_cast<size_t>(y) * v.width * 4;
            for (uint32_t x = 0; x < v.width; ++x) {
                const uint8_t a = src[x * 4 + 3];
                dst[x * 4 + 0] = static_cast<uint8_t>(src[x * 4 + 0] * a / 255);
                dst[x * 4 + 1] = static_cast<uint8_t>(src[x * 4 + 1] * a / 255);
                dst[x * 4 + 2] = static_cast<uint8_t>(src[x * 4 + 2] * a / 255);
                dst[x * 4 + 3] = a;
            }
        }
        uploadTex(entry.tex, premul.data(), v.width * 4);
    }

    void uploadAtlasIfNeeded() {
        if (!atlas.ready() || atlas.revision() == atlas_uploaded_revision) {
            return;
        }
        if (atlas_tex.w != static_cast<int>(atlas.width()) ||
            atlas_tex.h != static_cast<int>(atlas.height())) {
            destroyTex(atlas_tex);
            atlas_tex = createTex(static_cast<int>(atlas.width()),
                                  static_cast<int>(atlas.height()), WGPUTextureFormat_R8Unorm,
                                  WGPUTextureUsage_TextureBinding | WGPUTextureUsage_CopyDst);
        }
        uploadTex(atlas_tex, atlas.pixels(), atlas.width());
        atlas_uploaded_revision = atlas.revision();
    }

    // =======================================================================
    // drawing — mirrors vulkan_renderer.cpp (and thus the CPU reference)
    // =======================================================================

    static int blendIndex(Blend b) { return static_cast<int>(b); }

    struct MaskCtx {
        Tex* mask = nullptr;
        IRect box;           // mask region in target coords
        Mat23 inv_for_mask;  // mask px → local units
        float aa = 0;
    };

    bool beginMask(MaskCtx& ctx, Tex& target, const Mat23& m, const Mat23& inv, Rect local_bbox,
                   float pad_px, float aa) {
        ctx.box = targetBBox(m, local_bbox, pad_px, target.w, target.h);
        if (ctx.box.empty()) {
            return false;
        }
        endTarget();
        ctx.mask = acquireTransient(ctx.box.x1 - ctx.box.x0, ctx.box.y1 - ctx.box.y0,
                                    WGPUTextureFormat_R16Float);
        ctx.inv_for_mask = inv * Mat23::translation({static_cast<float>(ctx.box.x0),
                                                     static_cast<float>(ctx.box.y0)});
        ctx.aa = aa;
        ensureTarget(*ctx.mask);
        return true;
    }

    void maskPart(MaskCtx& ctx, const Mat23& m, Rect part_bbox, float pad_px, int mode,
                  const float pa[4], const float pb[4]) {
        IRect r = targetBBox(m, part_bbox, pad_px, ctx.box.x1, ctx.box.y1);
        r.x0 = std::max(r.x0, ctx.box.x0);
        r.y0 = std::max(r.y0, ctx.box.y0);
        if (r.empty()) {
            return;
        }
        Push push{};
        push.rect[0] = static_cast<float>(r.x0 - ctx.box.x0);
        push.rect[1] = static_cast<float>(r.y0 - ctx.box.y0);
        push.rect[2] = static_cast<float>(r.x1 - r.x0);
        push.rect[3] = static_cast<float>(r.y1 - r.y0);
        push.meta[0] = static_cast<float>(ctx.mask->w);
        push.meta[1] = static_cast<float>(ctx.mask->h);
        push.meta[2] = ctx.aa;
        push.meta[3] = static_cast<float>(mode);
        setInv(push, ctx.inv_for_mask);
        std::memcpy(push.pa, pa, sizeof push.pa);
        std::memcpy(push.pb, pb, sizeof push.pb);
        drawQuad(pipe_mask_shape, polygon_points.empty() ? dummy_group : points_group, push);
    }

    void maskGlyph(MaskCtx& ctx, const Mat23& m, Rect glyph_local, const float uv[4]) {
        IRect r = targetBBox(m, glyph_local, 1, ctx.box.x1, ctx.box.y1);
        r.x0 = std::max(r.x0, ctx.box.x0);
        r.y0 = std::max(r.y0, ctx.box.y0);
        if (r.empty()) {
            return;
        }
        Push push{};
        push.rect[0] = static_cast<float>(r.x0 - ctx.box.x0);
        push.rect[1] = static_cast<float>(r.y0 - ctx.box.y0);
        push.rect[2] = static_cast<float>(r.x1 - r.x0);
        push.rect[3] = static_cast<float>(r.y1 - r.y0);
        push.meta[0] = static_cast<float>(ctx.mask->w);
        push.meta[1] = static_cast<float>(ctx.mask->h);
        push.meta[2] = ctx.aa;
        setInv(push, ctx.inv_for_mask);
        push.pa[0] = glyph_local.x;
        push.pa[1] = glyph_local.y;
        push.pa[2] = glyph_local.w;
        push.pa[3] = glyph_local.h;
        std::memcpy(push.pb, uv, sizeof push.pb);
        drawQuad(pipe_mask_glyph, texGroup(atlas_tex.view, sampler_linear), push);
    }

    void finishMask(MaskCtx& ctx, Tex& target, Color color, float fold_alpha, Blend blend) {
        endTarget();
        ensureTarget(target);
        Push push{};
        setRect(push, ctx.box);
        push.meta[0] = static_cast<float>(target.w);
        push.meta[1] = static_cast<float>(target.h);
        push.pa[0] = fold_alpha;
        setColor(push, color);
        drawQuad(pipe_mask_comp[blendIndex(blend)], texGroup(ctx.mask->view, sampler_nearest),
                 push);
    }

    void drawRoundedRect(Tex& target, Rect r, float corner, float stroke_w, const Mat23& m,
                         Color color, float alpha, Blend blend) {
        if (r.w <= 0 || r.h <= 0 || color.a <= 0 || alpha <= 0) {
            return;
        }
        const float scale = scaleOf(m);
        if (scale <= 0) {
            return;
        }
        const IRect box = targetBBox(m, r, (stroke_w + 2) * scale, target.w, target.h);
        if (box.empty()) {
            return;
        }
        ensureTarget(target);
        Push push{};
        setRect(push, box);
        push.meta[0] = static_cast<float>(target.w);
        push.meta[1] = static_cast<float>(target.h);
        push.meta[2] = 1.0f / scale;
        setInv(push, m.inverse());
        const Vec2 center = r.center();
        push.pa[0] = center.x;
        push.pa[1] = center.y;
        push.pa[2] = r.w * 0.5f;
        push.pa[3] = r.h * 0.5f;
        push.pb[0] = std::min(corner, std::min(r.w, r.h) * 0.5f);
        push.pb[1] = stroke_w;
        push.px2[0] = alpha;
        setColor(push, color);
        drawQuad(pipe_shape_color[blendIndex(blend)], dummy_group, push);
    }

    void drawTextRun(Tex& target, const TextContent& c, const Mat23& m, const Mat23& inv,
                     Color color, float alpha, Blend blend, float scale) {
        ensureAtlas();
        if (!atlas.ready() || c.utf8.empty() || atlas_tex.tex == nullptr) {
            return;
        }
        const TextRun& run = textRun(c.utf8);
        const float s = c.size / static_cast<float>(atlas.pixelSize());
        float align_dx = 0;
        if (c.align != Align::Left) {
            const float w = run.width * s;
            align_dx = c.align == Align::Center ? -w * 0.5f : -w;
        }
        const Rect text_box = measureText(c);
        MaskCtx mask;
        if (!beginMask(mask, target, m, inv, rectPad(text_box, 2), 2 * scale, 1.0f / scale)) {
            return;
        }
        for (const auto& q : run.quads) {
            const Rect lq{c.position.x + align_dx + q.x * s, c.position.y + q.y * s, q.w * s,
                          q.h * s};
            const float uv[4] = {q.u0, q.v0, q.u1, q.v1};
            maskGlyph(mask, m, lq, uv);
        }
        finishMask(mask, target, color, alpha, blend);
    }

    void drawImageContent(Tex& target, const ImageContent& c, Rect bounds, const Mat23& m,
                          const Mat23& inv, float alpha, Blend blend) {
        auto it = image_cache.find(c.view.pixels);
        if (it == image_cache.end() || !c.view.valid() || bounds.w <= 0 || bounds.h <= 0) {
            return;
        }
        Tex& tex = it->second.tex;
        Rect src{0, 0, static_cast<float>(c.view.width), static_cast<float>(c.view.height)};
        if (c.source_rect.w > 0 && c.source_rect.h > 0) {
            src = plan::rectIntersect(c.source_rect, src);
        }
        if (src.w <= 0 || src.h <= 0) {
            return;
        }
        Rect dest = bounds;
        if (c.fit == Fit::Contain) {
            const float s = std::min(bounds.w / src.w, bounds.h / src.h);
            dest = {bounds.x + (bounds.w - src.w * s) * 0.5f,
                    bounds.y + (bounds.h - src.h * s) * 0.5f, src.w * s, src.h * s};
        } else if (c.fit == Fit::Cover) {
            const float s = std::max(bounds.w / src.w, bounds.h / src.h);
            const float vis_w = bounds.w / s;
            const float vis_h = bounds.h / s;
            src = {src.x + (src.w - vis_w) * 0.5f, src.y + (src.h - vis_h) * 0.5f, vis_w, vis_h};
        }
        const IRect box = targetBBox(m, dest, 1, target.w, target.h);
        if (box.empty()) {
            return;
        }
        ensureTarget(target);
        Push push{};
        setRect(push, box);
        push.meta[0] = static_cast<float>(target.w);
        push.meta[1] = static_cast<float>(target.h);
        setInv(push, inv);
        push.pa[0] = dest.x;
        push.pa[1] = dest.y;
        push.pa[2] = dest.w;
        push.pa[3] = dest.h;
        push.pb[0] = src.x;
        push.pb[1] = src.y;
        push.pb[2] = src.w;
        push.pb[3] = src.h;
        push.px2[0] = static_cast<float>(tex.w);
        push.px2[1] = static_cast<float>(tex.h);
        push.px2[2] = alpha;
        drawQuad(pipe_image[blendIndex(blend)], texGroup(tex.view, sampler_linear), push);
    }

    // Mirrors CpuRenderer::Impl::drawContent case by case.
    void drawContent(Tex& target, const Layer& layer, Rect bounds, const Mat23& m, float alpha) {
        const Content& content = layer.content();
        if (std::holds_alternative<std::monostate>(content)) {
            return;
        }
        const Mat23 inv = m.inverse();
        const float scale = scaleOf(m);
        if (scale <= 0) {
            return;
        }
        const float aa = 1.0f / scale;
        const float th = layer.thickness();
        const Color color = layer.colorValue();
        const Blend mode = layer.blendMode();
        const float pad_px = (th * 0.5f + 2.0f) * scale;

        MaskCtx mask;
        const auto begin = [&](Rect local_bbox, float extra_pad_logical) {
            return beginMask(mask, target, m, inv, local_bbox,
                             pad_px + extra_pad_logical * scale, aa);
        };
        const auto finish = [&] { finishMask(mask, target, color, alpha, mode); };

        const auto segPart = [&](const Seg& s, Cap capstyle) {
            float pa[4] = {s.a.x, s.a.y, s.b.x, s.b.y};
            float pb[4] = {capstyle == Cap::Butt ? th * 0.5f : th, 0, 0, 0};
            maskPart(mask, m, segBounds(s), pad_px,
                     capstyle == Cap::Butt ? SM_SEGMENT_BUTT : SM_SEGMENT_ROUND, pa, pb);
        };
        const auto strokeSegs = [&](const std::vector<Seg>& segs, Cap capstyle) {
            for (const Seg& s : segs) {
                segPart(s, capstyle);
            }
        };
        const auto roundedRectPart = [&](Rect r, float corner) {
            const Vec2 center = r.center();
            const float cr = std::min(corner, std::min(r.w, r.h) * 0.5f);
            float pa[4] = {center.x, center.y, r.w * 0.5f, r.h * 0.5f};
            float pb[4] = {cr, th, 0, 0};
            maskPart(mask, m, r, pad_px, SM_ROUNDED_RECT, pa, pb);
        };

        if (const auto* c = std::get_if<ImageContent>(&content)) {
            drawImageContent(target, *c, bounds, m, inv, alpha, mode);
        } else if (const auto* c = std::get_if<TextContent>(&content)) {
            drawTextRun(target, *c, m, inv, color, alpha, mode, scale);
        } else if (const auto* c = std::get_if<LineContent>(&content)) {
            if (begin(segBounds({c->from, c->to}), 0)) {
                strokeSegs(dashSegments({{c->from, c->to}}, layer.dashValue()), layer.capValue());
                finish();
            }
        } else if (const auto* c = std::get_if<PolylineContent>(&content)) {
            if (c->points.size() >= 2 && begin(layer.contentBounds(), 0)) {
                strokeSegs(dashSegments(pathSegments(c->points, false), layer.dashValue()),
                           layer.capValue());
                finish();
            }
        } else if (const auto* c = std::get_if<PolygonContent>(&content)) {
            if (c->points.size() >= 3 && begin(layer.contentBounds(), 0)) {
                if (th > 0) {
                    strokeSegs(dashSegments(pathSegments(c->points, true), layer.dashValue()),
                               layer.capValue());
                } else {
                    auto it = polygon_offsets.find(&layer);
                    if (it != polygon_offsets.end()) {
                        float pa[4] = {static_cast<float>(it->second),
                                       static_cast<float>(c->points.size()), 0, 0};
                        float pb[4] = {0, 0, 0, 0};
                        maskPart(mask, m, layer.contentBounds(), pad_px, SM_POLYGON, pa, pb);
                    }
                }
                finish();
            }
        } else if (const auto* c = std::get_if<RectContent>(&content)) {
            if (begin(c->rect, 0)) {
                roundedRectPart(c->rect, layer.cornerRadius());
                finish();
            }
        } else if (const auto* c = std::get_if<CircleContent>(&content)) {
            if (begin(layer.contentBounds(), 0)) {
                float pa[4] = {c->center.x, c->center.y, c->radius, th};
                float pb[4] = {0, 0, 0, 0};
                maskPart(mask, m, layer.contentBounds(), pad_px, SM_CIRCLE, pa, pb);
                finish();
            }
        } else if (const auto* c = std::get_if<CirclesContent>(&content)) {
            if (!c->centers.empty() && begin(layer.contentBounds(), 0)) {
                for (const Vec2& center : c->centers) {
                    const Rect b{center.x - c->radius, center.y - c->radius, 2 * c->radius,
                                 2 * c->radius};
                    float pa[4] = {center.x, center.y, c->radius, th};
                    float pb[4] = {0, 0, 0, 0};
                    maskPart(mask, m, b, pad_px, SM_CIRCLE, pa, pb);
                }
                finish();
            }
        } else if (const auto* c = std::get_if<ArcContent>(&content)) {
            if (begin(layer.contentBounds(), 0)) {
                constexpr float kPi = 3.14159265358979f;
                float a0 = c->start_deg * kPi / 180.0f;
                float a1 = c->end_deg * kPi / 180.0f;
                if (a1 < a0) {
                    std::swap(a0, a1);
                }
                a1 = std::min(a1, a0 + 2 * kPi);
                float pa[4] = {c->center.x, c->center.y, c->radius, a0};
                float pb[4] = {a1, th, 0, 0};
                maskPart(mask, m, layer.contentBounds(), pad_px, SM_ARC, pa, pb);
                finish();
            }
        } else if (const auto* c = std::get_if<ArrowContent>(&content)) {
            const float len = std::hypot(c->to.x - c->from.x, c->to.y - c->from.y);
            if (len > 1e-4f) {
                const float head = c->head_size > 0 ? c->head_size : std::max(3.0f * th, 9.0f);
                if (begin(rectPad(layer.contentBounds(), head), 0)) {
                    const Vec2 dir{(c->to.x - c->from.x) / len, (c->to.y - c->from.y) / len};
                    const Vec2 neck{c->to.x - dir.x * head, c->to.y - dir.y * head};
                    const Vec2 side{-dir.y * head * 0.5f, dir.x * head * 0.5f};
                    segPart({c->from, neck}, layer.capValue());
                    float pa[4] = {c->to.x, c->to.y, neck.x + side.x, neck.y + side.y};
                    float pb[4] = {neck.x - side.x, neck.y - side.y, 0, 0};
                    maskPart(mask, m, rectPad(segBounds({neck, c->to}), head), pad_px,
                             SM_TRIANGLE, pa, pb);
                    finish();
                }
            }
        } else if (const auto* c = std::get_if<CrosshairContent>(&content)) {
            if (begin(layer.contentBounds(), 0)) {
                const float gap = c->gap > 0 ? c->gap : c->size * 0.25f;
                const Vec2 o = c->center;
                const Seg ticks[4] = {{{o.x + gap, o.y}, {o.x + c->size, o.y}},
                                      {{o.x - gap, o.y}, {o.x - c->size, o.y}},
                                      {{o.x, o.y + gap}, {o.x, o.y + c->size}},
                                      {{o.x, o.y - gap}, {o.x, o.y - c->size}}};
                strokeSegs({ticks[0], ticks[1], ticks[2], ticks[3]}, layer.capValue());
                finish();
            }
        } else if (const auto* c = std::get_if<GridContent>(&content)) {
            if (begin(bounds, 0)) {
                const Vec2 center = bounds.center();
                float pa[4] = {c->spacing, th, 0, 0};
                float pb[4] = {center.x, center.y, bounds.w * 0.5f, bounds.h * 0.5f};
                maskPart(mask, m, bounds, pad_px, SM_GRID, pa, pb);
                finish();
            }
        } else if (const auto* c = std::get_if<BoxesContent>(&content)) {
            if (!c->smoothed.empty() && begin(rectPad(layer.contentBounds(), 20.0f), 0)) {
                for (const Box& box : c->smoothed) {
                    roundedRectPart(box.rect, layer.cornerRadius());
                }
                finish();
                if (c->show_label) {
                    for (const Box& box : c->smoothed) {
                        const std::string label = boxLabel(box);
                        if (label.empty()) {
                            continue;
                        }
                        TextContent t;
                        t.utf8 = label;
                        t.size = 14;
                        t.position = {box.rect.x + 2, std::max(box.rect.y - 18.0f, 0.0f)};
                        drawTextRun(target, t, m, inv, color, alpha, mode, scale);
                    }
                }
            }
        }
    }

    // =======================================================================
    // layer recursion — mirrors vulkan_renderer.cpp renderLayer
    // =======================================================================

    void renderLayer(Tex& target, const Layer& layer, const Mat23& parent_m, Vec2 parent_size) {
        if (layer.hidden()) {
            return;
        }
        const float opacity = layer.presentedOpacity();
        if (opacity <= 0) {
            return;
        }
        const Layer::Resolved r = layer.resolve(parent_size);
        const Mat23 m = parent_m * r.to_parent;
        const bool needs_offscreen = plan::needsOffscreen(layer, opacity);

        if (!needs_offscreen) {
            const Blend mode = layer.blendMode();
            drawRoundedRect(target, r.bounds, layer.cornerRadius(), 0, m,
                            layer.backgroundValue(), opacity, mode);
            drawContent(target, layer, r.bounds, m, opacity);
            for (const auto& child : layer.sublayers()) {
                renderLayer(target, *child, m, r.bounds.size());
            }
            if (layer.borderValue()) {
                drawRoundedRect(target, r.bounds, layer.cornerRadius(),
                                layer.borderValue()->width, m, layer.borderValue()->color,
                                opacity, mode);
            }
            return;
        }

        // ---- offscreen path ----
        const float scale = scaleOf(m);
        Rect ext = plan::subtreeExtent(layer, parent_size,
                                       [this](const TextContent& c) { return measureText(c); });
        if (ext.w <= 0 || ext.h <= 0 || scale <= 0) {
            return;
        }
        ext = rectPad(ext, 2.0f / scale);
        const int bw = std::max(1, static_cast<int>(std::ceil(ext.w * scale)));
        const int bh = std::max(1, static_cast<int>(std::ceil(ext.h * scale)));
        if (static_cast<int64_t>(bw) * bh > 64LL * 1024 * 1024) {
            return;
        }
        endTarget();
        Tex* buf = acquireTransient(bw, bh, WGPUTextureFormat_RGBA16Float);
        ensureTarget(*buf);  // clears
        const Mat23 mb = Mat23::scaling({scale, scale}) * Mat23::translation({-ext.x, -ext.y});

        drawRoundedRect(*buf, r.bounds, layer.cornerRadius(), 0, mb, layer.backgroundValue(),
                        1.0f, Blend::Normal);
        drawContent(*buf, layer, r.bounds, mb, 1.0f);
        for (const auto& child : layer.sublayers()) {
            renderLayer(*buf, *child, mb, r.bounds.size());
        }
        if (layer.borderValue()) {
            drawRoundedRect(*buf, r.bounds, layer.cornerRadius(), layer.borderValue()->width,
                            mb, layer.borderValue()->color, 1.0f, Blend::Normal);
        }

        // Filters: ping-pong through transients (fullscreen passes).
        for (const Filter& f : layer.filters()) {
            float values[5];
            plan::scaleFilterValues(f, scale, ext, static_cast<float>(bw),
                                    static_cast<float>(bh), values);
            if (f.mode == FS_BLUR) {
                buf = gaussianBlur(buf, values[0]);
                continue;
            }
            WGPUTextureView lut_view = nullptr;
            if (f.image.valid() && f.mode != FS_LUT && f.mode != FS_FACE &&
                f.mode != FS_TEXTURE) {
                // generic image parameter (sumie's paper): bind, never gate
                auto it = image_cache.find(f.image.pixels);
                if (it != image_cache.end()) {
                    lut_view = it->second.tex.view;
                }
            }
            if (f.mode == FS_LUT || f.mode == FS_FACE || f.mode == FS_TEXTURE) {
                // Unfed or malformed image parameter: the documented
                // pass-through (identical to the CPU reference).
                auto it = image_cache.find(f.image.pixels);
                if (it == image_cache.end() ||
                    (f.mode == FS_LUT &&
                     !lutAtlasGrid(f.image, &values[2], &values[3]))) {
                    continue;
                }
                lut_view = it->second.tex.view;
            }
            endTarget();
            Push push{};
            push.meta[3] = static_cast<float>(f.mode);
            push.pa[0] = values[0];
            push.pa[1] = values[1];
            push.pa[2] = values[2];
            push.pa[3] = values[3];
            push.pb[0] = values[4];
            // Stateful filters (persistent_buffers P1): advance the layer's
            // field one tick (read ping + source, write pong RAW), swap,
            // then let the normal pass below read the fresh field.
            WGPUTextureView state_view = nullptr;
            const FilterSpec* fspec = findFilterSpec(f.mode);
            if (fspec != nullptr && fspec->stateful) {
                FilterState& st = state_cache[{static_cast<const void*>(&layer), f.mode}];
                if (st.ping.w != bw || st.ping.h != bh) {
                    if (st.ping.tex != nullptr) {
                        destroyTex(st.ping);
                        destroyTex(st.pong);
                    }
                    const WGPUTextureUsage usage = static_cast<WGPUTextureUsage>(
                        WGPUTextureUsage_RenderAttachment | WGPUTextureUsage_TextureBinding);
                    st.ping = createTex(bw, bh, WGPUTextureFormat_RGBA32Float, usage);
                    st.pong = createTex(bw, bh, WGPUTextureFormat_RGBA32Float, usage);
                    // cold start is a documented zero field
                    ensureTarget(st.ping);
                    endTarget();
                    ensureTarget(st.pong);
                    endTarget();
                }
                st.frame_used = frame_counter;
                ensureTarget(st.pong);
                drawFullscreen(pipe_filter_state,
                               texGroup(buf->view, sampler_nearest, lut_view,
                                        sampler_linear, st.ping.view),
                               push);
                endTarget();
                std::swap(st.ping, st.pong);
                state_view = st.ping.view;
            }
            Tex* dst = acquireTransient(bw, bh, WGPUTextureFormat_RGBA16Float);
            ensureTarget(*dst);
            drawFullscreen(pipe_filter,
                           texGroup(buf->view, sampler_nearest, lut_view, sampler_linear,
                                    state_view),
                           push);
            buf->in_use = false;
            buf = dst;
        }

        if (layer.maskValue().valid()) {
            auto mit = image_cache.find(layer.maskValue().pixels);
            if (mit != image_cache.end()) {
                endTarget();
                Tex* dst = acquireTransient(bw, bh, WGPUTextureFormat_RGBA16Float);
                ensureTarget(*dst);
                Push push{};
                push.pa[0] = ext.w / std::max(r.bounds.w, 1e-4f);
                push.pa[1] = (ext.x - r.bounds.x) / std::max(r.bounds.w, 1e-4f);
                push.pa[2] = ext.h / std::max(r.bounds.h, 1e-4f);
                push.pa[3] = (ext.y - r.bounds.y) / std::max(r.bounds.h, 1e-4f);
                push.pb[0] = layer.maskInvertValue() ? 1.0f : 0.0f;
                push.pb[1] = layer.maskFeatherValue() * scale;
                drawFullscreen(pipe_layer_mask,
                               texGroup(buf->view, sampler_nearest, mit->second.tex.view,
                                        sampler_linear),
                               push);
                buf->in_use = false;
                buf = dst;
            }
        }

        endTarget();
        ensureTarget(target);

        const Mat23 inv = m.inverse();
        const float aa = 1.0f / scale;
        const IRect box = targetBBox(m, ext, 2, target.w, target.h);

        if (const auto& sh = layer.shadowValue()) {
            Tex* shadow_buf = gaussianBlurCopy(buf, sh->radius * scale, bw, bh);
            ensureTarget(target);
            const IRect sbox = targetBBox(
                m, rectPad({ext.x + sh->offset.x, ext.y + sh->offset.y, ext.w, ext.h},
                           sh->radius * 2),
                2, target.w, target.h);
            if (!sbox.empty()) {
                Push push{};
                setRect(push, sbox);
                push.meta[0] = static_cast<float>(target.w);
                push.meta[1] = static_cast<float>(target.h);
                push.meta[2] = aa;
                push.meta[3] = 2.0f;  // tint flag
                setInv(push, inv);
                push.pa[0] = ext.x + sh->offset.x;
                push.pa[1] = ext.y + sh->offset.y;
                push.pa[2] = scale;
                push.pa[3] = sh->opacity * opacity;
                setColor(push, sh->color);
                drawQuad(pipe_composite[blendIndex(Blend::Normal)],
                         texGroup(shadow_buf->view, sampler_linear), push);
            }
            shadow_buf->in_use = false;
        }

        if (!box.empty()) {
            Push push{};
            setRect(push, box);
            push.meta[0] = static_cast<float>(target.w);
            push.meta[1] = static_cast<float>(target.h);
            push.meta[2] = aa;
            push.meta[3] = layer.masksToBounds() ? 1.0f : 0.0f;
            setInv(push, inv);
            push.pa[0] = ext.x;
            push.pa[1] = ext.y;
            push.pa[2] = scale;
            push.pa[3] = opacity;
            const Vec2 center = r.bounds.center();
            push.pb[0] = center.x;
            push.pb[1] = center.y;
            push.pb[2] = r.bounds.w * 0.5f;
            push.pb[3] = r.bounds.h * 0.5f;
            push.px2[0] =
                std::min(layer.cornerRadius(), std::min(r.bounds.w, r.bounds.h) * 0.5f);
            drawQuad(pipe_composite[blendIndex(layer.blendMode())],
                     texGroup(buf->view, sampler_linear), push);
        }
        buf->in_use = false;
    }

    // Separable gaussian into fresh transients; consumes `src` and returns
    // the blurred image. Same weights as the CPU reference.
    Tex* gaussianBlur(Tex* src, float radius_px) {
        if (radius_px <= 0.01f) {
            return src;
        }
        const float sigma = radius_px * 0.5f;
        const int half = std::max(1, static_cast<int>(std::ceil(sigma * 2.5f)));
        Tex* current = src;
        for (int p = 0; p < 2; ++p) {
            endTarget();
            Tex* dst = acquireTransient(src->w, src->h, WGPUTextureFormat_RGBA16Float);
            ensureTarget(*dst);
            Push push{};
            push.pa[0] = p == 0 ? 1.0f : 0.0f;
            push.pa[1] = p == 0 ? 0.0f : 1.0f;
            push.pa[2] = sigma;
            push.pa[3] = static_cast<float>(half);
            drawFullscreen(pipe_blur, texGroup(current->view, sampler_nearest), push);
            current->in_use = false;
            current = dst;
        }
        return current;
    }

    // Blur without consuming the source (shadows blur a copy's alpha).
    Tex* gaussianBlurCopy(Tex* src, float radius_px, int w, int h) {
        endTarget();
        Tex* copy = acquireTransient(w, h, WGPUTextureFormat_RGBA16Float);
        ensureTarget(*copy);
        Push push{};
        push.pa[0] = 1.0f;
        push.pa[1] = 0.0f;
        push.pa[2] = std::max(radius_px * 0.5f, 1e-4f);
        push.pa[3] = static_cast<float>(
            std::max(1, static_cast<int>(std::ceil(radius_px * 0.5f * 2.5f))));
        // First blur pass doubles as the copy.
        drawFullscreen(pipe_blur, texGroup(src->view, sampler_nearest), push);
        endTarget();
        Tex* out = acquireTransient(w, h, WGPUTextureFormat_RGBA16Float);
        ensureTarget(*out);
        push.pa[0] = 0.0f;
        push.pa[1] = 1.0f;
        drawFullscreen(pipe_blur, texGroup(copy->view, sampler_nearest), push);
        copy->in_use = false;
        return out;
    }

    // =======================================================================
    // frame
    // =======================================================================

    // Records the whole scene into the float working target and leaves the
    // encoder open for the caller's final pass (present or unpremul).
    bool recordScene(Stage& stage, uint32_t out_w, uint32_t out_h, float dt) {
        if (status != Status::Ready) {
            return false;
        }
        stage.setTextMeasurer([this](const TextContent& c) { return measureText(c); });
        stage.advance(dt);
        ++frame_counter;

        if (canvas.w != static_cast<int>(out_w) || canvas.h != static_cast<int>(out_h)) {
            destroyTex(canvas);
            canvas = createTex(static_cast<int>(out_w), static_cast<int>(out_h),
                               WGPUTextureFormat_RGBA16Float,
                               WGPUTextureUsage_RenderAttachment |
                                   WGPUTextureUsage_TextureBinding);
        }

        encoder = wgpuDeviceCreateCommandEncoder(device, nullptr);
        bound_target = nullptr;
        pass = nullptr;
        for (PushChunk& c : push_chunks) {
            c.used = 0;
        }
        push_chunk_i = 0;
        text_runs.clear();
        polygon_offsets.clear();
        polygon_points.clear();

        // Pre-pass: queue writes (images, glyphs) precede the submit.
        prepassLayer(stage.root());
        uploadAtlasIfNeeded();
        for (auto it = image_cache.begin(); it != image_cache.end();) {
            if (it->second.frame_used + 60 < frame_counter) {
                destroyTex(it->second.tex);
                it = image_cache.erase(it);
            } else {
                ++it;
            }
        for (auto it = state_cache.begin(); it != state_cache.end();) {
            if (it->second.frame_used + 1 < frame_counter) {
                destroyTex(it->second.ping);
                destroyTex(it->second.pong);
                it = state_cache.erase(it);
            } else {
                ++it;
            }
        }
        }

        // Logical canvas → output mapping (identical to the CPU reference).
        const float W = stage.width();
        const float H = stage.height();
        float sx = out_w / W;
        float sy = out_h / H;
        if (stage.fit() == Fit::Contain) {
            sx = sy = std::min(sx, sy);
        } else if (stage.fit() == Fit::Cover) {
            sx = sy = std::max(sx, sy);
        }
        const Mat23 m0 = Mat23::translation({(out_w - W * sx) * 0.5f, (out_h - H * sy) * 0.5f}) *
                         Mat23::scaling({sx, sy});

        canvas.needs_clear = true;
        ensureTarget(canvas);
        renderLayer(canvas, stage.root(), m0, {W, H});
        endTarget();
        return true;
    }

    // Flushes CPU-side buffers, submits, and releases per-frame objects.
    void submitFrame() {
        WGPUCommandBuffer cmd = wgpuCommandEncoderFinish(encoder, nullptr);
        wgpuCommandEncoderRelease(encoder);
        encoder = nullptr;
        flushPushChunks();
        if (!polygon_points.empty()) {
            const size_t bytes = std::min(polygon_points.size() * sizeof(Vec2),
                                          sizeof(float) * 2 * 65536);
            wgpuQueueWriteBuffer(queue, points_buf, 0, polygon_points.data(), bytes);
        }
        wgpuQueueSubmit(queue, 1, &cmd);
        wgpuCommandBufferRelease(cmd);
        for (WGPUBindGroup g : frame_groups) {
            wgpuBindGroupRelease(g);
        }
        frame_groups.clear();
        releaseAllTransients();
    }

    // ---- present path (the reason this backend exists) ---------------------

    bool renderToCanvas(Stage& stage, uint32_t out_w, uint32_t out_h, float dt) {
        if (surface == nullptr || pipe_present == nullptr) {
            fail("renderToCanvas without a canvas surface");
            return false;
        }
        if (surface_w != static_cast<int>(out_w) || surface_h != static_cast<int>(out_h)) {
            WGPUSurfaceConfiguration cfg = WGPU_SURFACE_CONFIGURATION_INIT;
            cfg.device = device;
            cfg.format = surface_format;
            cfg.usage = WGPUTextureUsage_RenderAttachment;
            cfg.width = out_w;
            cfg.height = out_h;
            cfg.alphaMode = WGPUCompositeAlphaMode_Premultiplied;
            cfg.presentMode = WGPUPresentMode_Fifo;
            wgpuSurfaceConfigure(surface, &cfg);
            surface_w = static_cast<int>(out_w);
            surface_h = static_cast<int>(out_h);
        }
        if (!recordScene(stage, out_w, out_h, dt)) {
            return false;
        }

        WGPUSurfaceTexture st = WGPU_SURFACE_TEXTURE_INIT;
        wgpuSurfaceGetCurrentTexture(surface, &st);
        if (st.status != WGPUSurfaceGetCurrentTextureStatus_SuccessOptimal &&
            st.status != WGPUSurfaceGetCurrentTextureStatus_SuccessSuboptimal) {
            wgpuCommandEncoderRelease(encoder);
            encoder = nullptr;
            fail("surface texture unavailable (status " +
                 std::to_string(static_cast<int>(st.status)) + ")");
            return false;
        }
        WGPUTextureView target_view = wgpuTextureCreateView(st.texture, nullptr);
        beginPass(target_view, true);
        Push push{};
        drawFullscreen(pipe_present, texGroup(canvas.view, sampler_nearest), push);
        wgpuRenderPassEncoderEnd(pass);
        wgpuRenderPassEncoderRelease(pass);
        pass = nullptr;

        submitFrame();
        wgpuTextureViewRelease(target_view);
        wgpuTextureRelease(st.texture);
        return true;
    }

    // ---- readback path (pixel comparison; async by browser decree) ---------

    bool readbackBegin(Stage& stage, uint32_t out_w, uint32_t out_h, float dt) {
        if (readback_pending) {
            return false;
        }
        if (!recordScene(stage, out_w, out_h, dt)) {
            return false;
        }
        return readbackFinish(out_w, out_h, sampler_nearest);
    }

    // Readback WITHOUT a second scene render: blits whatever the display
    // path last recorded into the canvas texture, rescaled to the
    // requested extent. Feedback loops (lsd.html's echo) otherwise pay a
    // full re-render per frame — and when their size differs from the
    // display's, recordScene destroys/recreates the canvas texture twice
    // every frame.
    bool readbackLastFrame(uint32_t out_w, uint32_t out_h) {
        if (readback_pending || status != Status::Ready || canvas.tex == nullptr) {
            return false;
        }
        encoder = wgpuDeviceCreateCommandEncoder(device, nullptr);
        bound_target = nullptr;
        pass = nullptr;
        for (PushChunk& c : push_chunks) {
            c.used = 0;
        }
        push_chunk_i = 0;
        text_runs.clear();
        polygon_offsets.clear();
        polygon_points.clear();
        return readbackFinish(out_w, out_h, sampler_linear);
    }

    // Shared tail: blit canvas → out_rgba, copy to the map buffer, submit,
    // and arm the async map. Assumes `encoder` is live.
    bool readbackFinish(uint32_t out_w, uint32_t out_h, WGPUSampler sampler) {
        if (out_rgba.w != static_cast<int>(out_w) || out_rgba.h != static_cast<int>(out_h)) {
            destroyTex(out_rgba);
            out_rgba = createTex(static_cast<int>(out_w), static_cast<int>(out_h),
                                 WGPUTextureFormat_RGBA8Unorm,
                                 WGPUTextureUsage_RenderAttachment | WGPUTextureUsage_CopySrc);
            if (readback_buf != nullptr) {
                wgpuBufferRelease(readback_buf);
            }
            readback_bpr = (out_w * 4 + 255u) & ~255u;
            readback_buf = createBuffer(static_cast<uint64_t>(readback_bpr) * out_h,
                                        WGPUBufferUsage_MapRead | WGPUBufferUsage_CopyDst);
        }
        readback_w = static_cast<int>(out_w);
        readback_h = static_cast<int>(out_h);

        out_rgba.needs_clear = true;
        ensureTarget(out_rgba);
        Push push{};
        drawFullscreen(pipe_unpremul, texGroup(canvas.view, sampler), push);
        endTarget();

        WGPUTexelCopyTextureInfo src = WGPU_TEXEL_COPY_TEXTURE_INFO_INIT;
        src.texture = out_rgba.tex;
        WGPUTexelCopyBufferInfo dst = WGPU_TEXEL_COPY_BUFFER_INFO_INIT;
        dst.layout.bytesPerRow = readback_bpr;
        dst.layout.rowsPerImage = out_h;
        dst.buffer = readback_buf;
        WGPUExtent3D extent = {out_w, out_h, 1};
        wgpuCommandEncoderCopyTextureToBuffer(encoder, &src, &dst, &extent);

        submitFrame();

        readback_pending = true;
        readback_ready = false;
        WGPUBufferMapCallbackInfo cb = {};
        cb.mode = WGPUCallbackMode_AllowSpontaneous;
        cb.callback = &Impl::onMapped;
        cb.userdata1 = this;
        wgpuBufferMapAsync(readback_buf, WGPUMapMode_Read, 0,
                           static_cast<size_t>(readback_bpr) * out_h, cb);
        return true;
    }

    static void onMapped(WGPUMapAsyncStatus s, WGPUStringView msg, void* userdata1, void*) {
        Impl* self = static_cast<Impl*>(userdata1);
        self->readback_pending = false;
        if (s != WGPUMapAsyncStatus_Success) {
            self->fail("readback map failed: " + toString(msg));
            return;
        }
        const uint8_t* mapped = static_cast<const uint8_t*>(wgpuBufferGetConstMappedRange(
            self->readback_buf, 0, static_cast<size_t>(self->readback_bpr) * self->readback_h));
        const size_t row = static_cast<size_t>(self->readback_w) * 4;
        self->out_pixels.resize(row * self->readback_h);
        for (int y = 0; y < self->readback_h; ++y) {
            std::memcpy(self->out_pixels.data() + row * y, mapped + self->readback_bpr * y, row);
        }
        wgpuBufferUnmap(self->readback_buf);
        self->readback_ready = true;
    }
};

// ===========================================================================
// WebGPURenderer
// ===========================================================================

WebGPURenderer::WebGPURenderer(Options options) : impl_(new Impl) {
    impl_->options = std::move(options);
    impl_->start();
}

WebGPURenderer::~WebGPURenderer() = default;

WebGPURenderer::Status WebGPURenderer::status() const { return impl_->status; }

const std::string& WebGPURenderer::error() const { return impl_->error; }

bool WebGPURenderer::renderToCanvas(Stage& stage, uint32_t out_w, uint32_t out_h, float dt) {
    return impl_->renderToCanvas(stage, out_w, out_h, dt);
}

bool WebGPURenderer::readbackLastFrame(uint32_t out_w, uint32_t out_h) {
    return impl_->readbackLastFrame(out_w, out_h);
}

bool WebGPURenderer::readbackBegin(Stage& stage, uint32_t out_w, uint32_t out_h, float dt) {
    return impl_->readbackBegin(stage, out_w, out_h, dt);
}

const uint8_t* WebGPURenderer::readbackPixels() const {
    return impl_->readback_ready ? impl_->out_pixels.data() : nullptr;
}

}  // namespace fluent_scene

#endif  // FS_HAVE_WEBGPU
